apiVersion: v1
kind: Service
metadata:
  name: service-meats
  labels:
    app: doprr
    microservice: meats
spec:
  type: NodePort
  ports: 
  - name: http
    port: 5009
    targetPort: 5009
  selector:
    app: doprr
    microservice: meats
    component: api