version: '3.3'

#used for the docker run
services:
  proxy:
    command: --api --docker --docker.domain=docker.localhost --logLevel=DEBUG  --docker.exposedbydefault=true
    networks:
      - webgateway
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
  app:
    
    networks:
      - webgateway
  meats.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MEATS_DATABASE=Server=meats.database;User Id=meats-api;Password=eltiempo;Database=doprr_meats;
      - MEATS_DATABASE_MIGRATION=Server=meats.database;User Id=doprr;Password=eltiempo!;Database=doprr_meats;
      - MEATS_DATABASE_LAST_RETRY_IN_SECONDS=20

    networks:
      - webgateway
  recipes.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MEATS_DATABASE=Server=recipes.database;User Id=recipes-api;Password=eltiempo;Database=doprr_recipes;
      - MEATS_DATABASE_MIGRATION=Server=recipes.database;User Id=doprr;Password=eltiempo!;Database=doprr_recipes;
      - MEATS_DATABASE_LAST_RETRY_IN_SECONDS=20

    networks:
      - webgateway
  ocpizzas.database:
    networks:
      webgateway:
        aliases:
          - meats.database
          - recipes.database
    ports:
      - 3306:3306
    volumes:
      - ocpizzas_data:/var/lib/mysql
networks:
  webgateway:
    driver: bridge

volumes:
  ocpizzas_data:
